# The Version to use and the Build Image
version: "1.0.0.{build}"
image: Visual Studio 2019 Preview

# Ditto, but for new csproj files (VS 2017 and newer)
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: "{version}"
  package_version: "{version}"
  assembly_version: "{version}"
  file_version: "{version}"
  informational_version: "{version}"

# If this build is from a tag, use the tag as the version without the V at the start
init:
  - ps: if ($env:APPVEYOR_REPO_TAG -eq "true") { Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v"))" }

# Restore Git Submodules and NuGet Packages
install:
  - git submodule update --init --recursive
  - nuget restore %APPVEYOR_PROJECT_NAME%.sln

# Build the solution with the same name as the AppVeyor project
build_script:
  - msbuild %APPVEYOR_PROJECT_NAME%.sln /t:Build /p:Configuration=Release
